name: toddpocalypse-infra
description: "GerdQuest: Idle Depths cloud save infrastructure"
runtime:
  name: nodejs
  options:
    packagemanager: npm
config:
  pulumi:tags:
    value:
      pulumi:template: aws-typescript
